[params]

  description = "Thoughts and projects on my IT life."
  author = "Mika Schulz"
  github = "https://github.com/MikaSchulz"
  linkedin = "https://www.linkedin.com/in/mika-schulz-538b5a246/"

