[params]

  description = "Thoughts and projects on my IT life."
  author = "Mika Schulz"
  github = "https://github.com/MikaSchulz"
  linkedin = "https://www.linkedin.com/in/mika-schulz-538b5a246/"

  # Color Configuration
  # Customize your website colors using standard web formats:
  # - Hexadecimal: #RRGGBB or #RGB (e.g., "#FFFFFF" or "#FFF")
  # - RGB/RGBA: rgb(r,g,b) or rgba(r,g,b,a) (e.g., "rgb(255,255,255)" or "rgba(255,255,255,0.9)")
  # - Named colors: CSS color names (e.g., "white", "black", "blue")
  # All colors are validated at build time for format and WCAG AA accessibility standards.

  [params.colors]
    # Core colors (Priority P1)
    background = "#01161e"           # Main page background color
    text = "#FFFFFF"                 # Primary text color
    link = "#FFFFFF"                 # Link color
    linkHover = "#FFFFFF"            # Link hover/focus state color

    # Interactive elements (Priority P2)
    navigationLink = "#FFFFFF"       # Navigation menu link color
    button = "#ff6d00"               # Button color
    headerBackground = "#124559"     # Header background color
    footerBackground = "#124559"     # Footer background color

    # Accent and semantic colors (Priority P3)
    headingPrimary = "#1a1a1a"       # Primary heading color (h1, h2)
    headingSecondary = "#333333"     # Secondary heading color (h3, h4, h5, h6)
    codeBackground = "#f5f5f5"       # Code block background color
    codeText = "#333333"             # Code block text color
    metadata = "#666666"             # Metadata text color (dates, categories, tags)
    border = "#e0e0e0"               # Border and divider color
